# Generated by Django 5.0 on 2023-12-20 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medecine', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medecine',
            old_name='favoris',
            new_name='favorite',
        ),
    ]
