# Generated by Django 5.0 on 2023-12-21 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecine', '0002_rename_favoris_medecine_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medecine',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
