# Generated by Django 5.0 on 2023-12-21 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medecine', '0003_alter_medecine_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medecine',
            options={'verbose_name': 'Medecine', 'verbose_name_plural': 'Medecines'},
        ),
    ]
