# Generated by Django 5.0 on 2023-12-21 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecine', '0004_alter_medecine_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='medecine',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='imgs/'),
        ),
    ]
