# Generated by Django 5.0 on 2023-12-21 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecine', '0005_medecine_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='medecine',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
